[package]
name = "givre-compiles-in-nostd-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
givre = { path = "../../givre", default-features = false, features = ["all-ciphersuites", "spof"] }

